---
title: "Progress log"
---

## To-do

* [ ] Write up introduction and motivation
* [ ] Write up Data Science Questions
* [ ] Conduct Literature Review
* [ ] Data Collection
* [ ] Data Cleaning
* [ ] Exploratory Data Analysis
* [ ] Dimensionality Reduction
* [ ] Clustering Analysis
* [ ] Supervised Learning
* [ ] Technical Report
* [ ] Non-Technical Report

## Munashe Mhlanga:

[About Me](../index.qmd#about-us)

Project roles:

* [x] Data Collection
* [x] Data Cleaning
* [x] Exploratory Data Analysis
* [x] Supervised Learning
* [x] Technical Report

**Weekly project contribution log:**


**10-27-2025** 

* [x] Brainstormed topics and landed on predicting floods and droughts in sub-saharan Africa


**11-03-2025** 

* [x] Data Collection through NOAA (National Oceanic and Atmospheric Administration) climate data

**11-10-2025** 

* [x] Literature Review and drop of initial project due to have reliance on time series methods. Project focus only required traditional machine learning methods that do not work on time series

**11-17-2025** 

* [x] Project brainstorm with partner, landing on predicting survival time for breast cancer and cervical cancer while comparing impact of factors on mortality e.g., age at diagnosis
* [x] Data Collection

**11-24-2025** 

* [x] Project management and detailed workplan
* [x] Data Cleaning

**12-01-2025** 

* [x] Exploratory Data Analysis

**12-08-2025** 

* [x] Supervised Learning

**12-12-2025** 

* [x] Technical Report
* [x] Website edits


## Betsiet Delelegn

[About Me](../index.qmd#about-us)

Project roles:

* [x] Literature Review
* [x] Dimensionality Reduction
* [x] Clustering Analysis (Unsupervised Learning)
* [x] Non-Technical Report

**Weekly project contribution log:**

**11-08-2025** 

* [x] Brainstormed topics; initially explored Cherry Blossom Prediction data and NOAA API

**11-15-2025** 

* [x] Pivoted to breast cancer data for project focus

**11-17-2025** 

* [x] Project brainstorm with partner, landing on breast and cervical cancer survival analysis using TCGA data
* [x] Began literature review on cancer survival patterns and TCGA methodology

**12-02-2025** 

* [x] Initial dimensionality reduction experiments 

**12-06-2025** 

* [x] Completed dimensionality reduction 
* [x] Clustering analysis—K
* [x] Statistical validation

**12-13-2025** 

* [x] Finalized unsupervised learning notebook
* [x] Non-technical report

**12-16-2025** 

* [x] Final revisions 